# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

pool:
  vmImage: ubuntu-16.04

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Install-Module -Name Pester -Force -Scope CurrentUser -verbose; Invoke-Pester -Script $(Build.SourcesDirectory)/CI -OutputFile $(Build.SourcesDirectory)/TEST-ARM.xml -OutputFormat NUnitXML -EnableExit'    

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/TEST-*.xml'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: |
     template/**
     scripts/**
     policy/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'